In [1]:
import os
os.cpu_count()

36

In [2]:
from socket import gethostname
gethostname()

'srv006542.fr.cfm.fr'

In [1]:
test = None
if test:
    print(dingo)

In [1]:
dic_items = {  # Assets.
            "Cash": 0.0,
            "Securities Usable": 0.0,
            "Securities Encumbered": 0.0,
            "Loans": 0.0,
            "Reverse Repos": 0.0,
            "Own Funds": 0.0,
            "Deposits": 2,
            "Repos": 0.0,
            "MROs": 0.0,
            "Securities Collateral": 0.0,
            "Securities Reused": 0.0,
        }

In [3]:
import pandas as pd


In [6]:
import parameters as par

sr_accounting_items[par.assets].sum()

0

In [2]:
import parameters as par
import numpy as np

dict.fromkeys(par.matrices,np.zeros((4,5)))

{'adjency': array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 'trust': array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 'binary_adjency': array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])}

In [13]:
import pandas as pd
ind = pd.MultiIndex.from_tuples([], names=(u'one', u'two', u'three'))
df = pd.DataFrame(columns=['alpha', 'beta'], index=ind)
df.loc["bank a","transaction 1","time 56"] = [0.2,True]
df.loc["bank a","transaction 2","time 57"] = [0.3,True]
df.loc["bank b","transaction 2","time 57"] = [0.3,False]
df

alpha   beta
one    two           three                
bank a transaction 1 time 56    0.2   True
       transaction 2 time 57    0.3   True
bank b transaction 2 time 57    0.3  False

In [14]:
df[df["beta"]]

alpha  beta
one    two           three               
bank a transaction 1 time 56    0.2  True
       transaction 2 time 57    0.3  True

In [2]:
for i in range(1):
    print(i)

0


# dictionaries of arrays or dataframes

In [25]:
import parameters as par
import numpy as np
dic_matrices = dict.fromkeys(par.matrices)
for key in dic_matrices.keys():
    dic_matrices[key] = np.zeros((3, 3)).copy()

In [26]:
dic_matrices["adjency"][1,1] = 1
dic_matrices["adjency"]

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])

In [27]:
dic_matrices["trust"]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [1]:
import pandas as pd
df_reverse_repos = pd.read_csv("./results/single_run/df_reverse_repos.csv",index_col=0)

In [5]:
df = df_reverse_repos[df_reverse_repos["status"]==True]

In [11]:
import numpy as np
np.isnan(df["maturity"].iloc[0])

True

In [13]:
dico =dict.fromkeys([1,2,3])
dico

{1: None, 2: None, 3: None}

In [14]:
dico[1] = pd.DataFrame(data=[1,2])

In [15]:
dico

{1:    0
 0  1
 1  2,
 2: None,
 3: None}

In [18]:
np.zeros((3,4),dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

# bug analysis

In [1]:
import pickle

bank_id_on_balance_repos = pickle.load(open("./support/bank_id_on_balance_repos.pickle","rb"))

In [2]:
bank_id_on_balance_repos

{0: 0.0,
 2: 0.0,
 3: 0.0,
 4: 0.0,
 5: 0.0,
 6: 0.0,
 7: 0.0,
 8: 0.0,
 9: 0.0,
 10: 0.0,
 11: 0.0,
 12: 0.0,
 13: 0.0,
 14: 10.954668041922574,
 15: 0.0,
 16: 3.3377515568204394,
 17: 2.220446049250313e-16,
 18: 3.481925308088402,
 19: 0.0,
 20: 0.0,
 21: 0.0,
 22: 0.0,
 23: 0.0,
 24: 0.0,
 25: 0.0,
 26: 0.0,
 27: 0.0,
 28: 0.0,
 29: 0.0,
 30: 0.0,
 31: 0.0,
 32: 0.0,
 33: 0.0,
 34: 0.0,
 35: 0.0,
 36: 0.0,
 37: 0.0,
 38: 0.0,
 39: 0.0,
 40: 0.0,
 41: 0.0,
 42: 0.0,
 43: 0.0,
 44: 0.0,
 45: 0.0,
 46: 0.0,
 47: 0.0,
 48: 2.1785106640798877,
 49: 0.0}