In [1]:
import os
os.cpu_count()

36

In [2]:
from socket import gethostname
gethostname()

'srv006542.fr.cfm.fr'

In [1]:
test = None
if test:
    print(dingo)

In [1]:
dic_items = {  # Assets.
            "Cash": 0.0,
            "Securities Usable": 0.0,
            "Securities Encumbered": 0.0,
            "Loans": 0.0,
            "Reverse Repos": 0.0,
            "Own Funds": 0.0,
            "Deposits": 2,
            "Repos": 0.0,
            "MROs": 0.0,
            "Securities Collateral": 0.0,
            "Securities Reused": 0.0,
        }

In [3]:
import pandas as pd


In [6]:
import parameters as par

sr_accounting_items[par.assets].sum()

0

In [2]:
import parameters as par
import numpy as np

dict.fromkeys(par.matrices,np.zeros((4,5)))

{'adjency': array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 'trust': array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 'binary_adjency': array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])}

In [13]:
import pandas as pd
ind = pd.MultiIndex.from_tuples([], names=(u'one', u'two', u'three'))
df = pd.DataFrame(columns=['alpha', 'beta'], index=ind)
df.loc["bank a","transaction 1","time 56"] = [0.2,True]
df.loc["bank a","transaction 2","time 57"] = [0.3,True]
df.loc["bank b","transaction 2","time 57"] = [0.3,False]
df

alpha   beta
one    two           three                
bank a transaction 1 time 56    0.2   True
       transaction 2 time 57    0.3   True
bank b transaction 2 time 57    0.3  False

In [14]:
df[df["beta"]]

alpha  beta
one    two           three               
bank a transaction 1 time 56    0.2  True
       transaction 2 time 57    0.3  True

In [2]:
for i in range(1):
    print(i)

0


# dictionaries of arrays or dataframes

In [25]:
import parameters as par
import numpy as np
dic_matrices = dict.fromkeys(par.matrices)
for key in dic_matrices.keys():
    dic_matrices[key] = np.zeros((3, 3)).copy()

In [26]:
dic_matrices["adjency"][1,1] = 1
dic_matrices["adjency"]

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])

In [27]:
dic_matrices["trust"]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [1]:
import pandas as pd
df_reverse_repos = pd.read_csv("./results/single_run/df_reverse_repos.csv",index_col=0)

In [5]:
df = df_reverse_repos[df_reverse_repos["status"]==True]

In [11]:
import numpy as np
np.isnan(df["maturity"].iloc[0])

True

In [13]:
dico =dict.fromkeys([1,2,3])
dico

{1: None, 2: None, 3: None}

In [14]:
dico[1] = pd.DataFrame(data=[1,2])

In [15]:
dico

{1:    0
 0  1
 1  2,
 2: None,
 3: None}

In [18]:
np.zeros((3,4),dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

# bug analysis

In [1]:
import pickle

bank_id_on_balance_repos = pickle.load(open("./support/bank_id_on_balance_repos.pickle","rb"))

# df_reverse analysis

In [3]:
import pandas as pd

df_reverse_repos = pd.read_csv("./results/single_run_saved/df_reverse_repos.csv",index_col=0)

In [4]:
df_reverse_repos

bank_id  trans_id        amount  start_step  tenor  status
owner_bank_id                                                            
0                  414         0  2.251317e-01          71    2.0   False
0                  193         0  2.177591e+00          72   24.0   False
0                  414         1  0.000000e+00          71    2.0   False
0                  278         0  2.047012e+00          73    3.0   False
0                  474         0  1.914228e+00          73    5.0   False
...                ...       ...           ...         ...    ...     ...
499                431       164  3.558560e-01        2491    3.0   False
499                431       165  1.110223e-16        2494    NaN    True
499                431       166  1.131620e+00        2491    4.0   False
499                431       167  9.388488e-01        2496    NaN    True
499                431       168  1.444025e+00        2493    6.0   False

[1152011 rows x 6 columns]